### PR TITLE
Make the fine-grained mode scheduler respect

### PR DESCRIPTION
**Pull request by dragos**
spark.mesos.mesosExecutor.cores when launching Mesos executors (regression)

### CODE REVIEW

**Comment by dragos** [comment]
I'm working on another fix for SPARK-7874, and will remove some of the duplication in tests, but I wanted to keep this PR as simple as possible (in line with the trivial fix).

**Comment by deanwampler** [comment]
Looks good to me.

**Comment by typesafe-tools** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://ci.typesafe.com/job/ghprb-spark-multi-conf/67/

**Build Log**
_last 10 lines_

```
[...truncated 18 lines...]
 > git config core.sparsecheckout # timeout=10
 > git checkout -f 1b0e407fbf91c709b24dfaf7a6e05d0b5bac82a0
First time build. Skipping changelog.
Triggering ghprb-spark-multi-conf » Spark-Ora-JDK7-PV,2.10
Configuration ghprb-spark-multi-conf » Spark-Ora-JDK7-PV,2.10 is still in the queue: Waiting for next available executor on Spark JDK-7 PV (i-c3945c16)
Configuration ghprb-spark-multi-conf » Spark-Ora-JDK7-PV,2.10 is still in the queue: Waiting for next available executor on Spark-Ora-JDK7-PV
ghprb-spark-multi-conf » Spark-Ora-JDK7-PV,2.10 completed with result FAILURE
Notifying upstream projects of job completion
Setting status of 5cd93439168bf3f95c53cbcdab288f03d4960c24 to FAILURE with url http://ci.typesafe.com/job/ghprb-spark-multi-conf/67/ and message: Merged build finished.
```

Test FAILed.

**Comment by typesafe-tools** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://ci.typesafe.com/job/ghprb-spark-multi-conf/68/

**Build Log**
_last 10 lines_

```
[...truncated 16 lines...]
 > git rev-parse refs/remotes/origin/origin/pr/21/merge^{commit} # timeout=10
Checking out Revision f255b802132feeb03df1c66fe3aa86b1bccfcd74 (refs/remotes/origin/pr/21/merge)
 > git config core.sparsecheckout # timeout=10
 > git checkout -f f255b802132feeb03df1c66fe3aa86b1bccfcd74
First time build. Skipping changelog.
Triggering ghprb-spark-multi-conf » Spark-Ora-JDK7-PV,2.10
ghprb-spark-multi-conf » Spark-Ora-JDK7-PV,2.10 completed with result FAILURE
Notifying upstream projects of job completion
Setting status of 03e8d0a620301c0bfd2bbf21415f7d794da19603 to FAILURE with url http://ci.typesafe.com/job/ghprb-spark-multi-conf/68/ and message: Merged build finished.
```

Test FAILed.

**Pull request closed without merging**
