### PR TITLE
Add Kafka modules to the 2.11 build.

### PR DESCRIPTION
**Pull request by dragos**

### CODE REVIEW

**Comment by dragos** [comment]
retest this please

**Comment by typesafe-tools** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://ci.typesafe.com/job/ghprb-spark-multi-conf/1/
Test PASSed.

**Comment by dragos** [comment]
retest this please

**Comment by typesafe-tools** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://ci.typesafe.com/job/ghprb-spark-multi-conf/2/

**Build Log**
_last 10 lines_

```
[...truncated 13 lines...]
 > git config core.sparsecheckout # timeout=10
 > git checkout -f 089d2aab9f764ac9e898a27139c72bc4f5cdee1e
First time build. Skipping changelog.
Triggering ghprb-spark-multi-conf » 2.11
Triggering ghprb-spark-multi-conf » 2.10
ghprb-spark-multi-conf » 2.11 completed with result FAILURE
ghprb-spark-multi-conf » 2.10 completed with result FAILURE
Notifying upstream projects of job completion
Setting status of aa15d99880169deb9166bf5fac944e4582398eb0 to FAILURE with url http://ci.typesafe.com/job/ghprb-spark-multi-conf/2/ and message: Merged build finished.
```

Test FAILed.

**Comment by dragos** [comment]
retest this please

**Comment by typesafe-tools** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://ci.typesafe.com/job/ghprb-spark-multi-conf/3/

**Build Log**
_last 10 lines_

```
[...truncated 16 lines...]
Triggering ghprb-spark-multi-conf » Spark-Ora-JDK7-PV,2.10
Triggering ghprb-spark-multi-conf » Spark-Ora-JDK7-PV,2.11
Configuration ghprb-spark-multi-conf » Spark-Ora-JDK7-PV,2.10 is still in the queue: Waiting for next available executor on Spark JDK-7 PV (i-dba1a126)
ghprb-spark-multi-conf » Spark-Ora-JDK7-PV,2.10 completed with result FAILURE
Aborted
Aborted by Iulian Dragoș
Interrupting #3
Notifying upstream projects of job completion
Setting status of aa15d99880169deb9166bf5fac944e4582398eb0 to FAILURE with url http://ci.typesafe.com/job/ghprb-spark-multi-conf/3/ and message: Merged build finished.
```

Test FAILed.

**Comment by dragos** [comment]
retest this please

**Comment by typesafe-tools** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://ci.typesafe.com/job/ghprb-spark-multi-conf/4/

**Build Log**
_last 10 lines_

```
[...truncated 15 lines...]
First time build. Skipping changelog.
Triggering ghprb-spark-multi-conf » Spark-Ora-JDK7-PV,2.10
Triggering ghprb-spark-multi-conf » Spark-Ora-JDK7-PV,2.11
Configuration ghprb-spark-multi-conf » Spark-Ora-JDK7-PV,2.10 is still in the queue: Waiting for next available executor on Spark JDK-7 PV (i-dba1a126)
Configuration ghprb-spark-multi-conf » Spark-Ora-JDK7-PV,2.10 is still in the queue: Waiting for next available executor on Spark-Ora-JDK7-PV
ghprb-spark-multi-conf » Spark-Ora-JDK7-PV,2.10 completed with result FAILURE
ghprb-spark-multi-conf » Spark-Ora-JDK7-PV,2.11 completed with result FAILURE
Notifying upstream projects of job completion
Setting status of aa15d99880169deb9166bf5fac944e4582398eb0 to FAILURE with url http://ci.typesafe.com/job/ghprb-spark-multi-conf/4/ and message: Merged build finished.
```

Test FAILed.

**Pull request closed without merging**
