### PR TITLE
testing

### PR DESCRIPTION
**Pull request by nraychaudhuri**

### CODE REVIEW

**Comment by nraychaudhuri** [comment]
ok to test

**Comment by typesafe-tools** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://ci.typesafe.com/job/ghprb-spark-multi-conf/63/

**Build Log**
_last 10 lines_

```
[...truncated 11 lines...]
 > git rev-parse refs/remotes/origin/origin/pr/20/merge^{commit} # timeout=10
Checking out Revision e27491b77e327239bf0765975ff0f8445782deb0 (refs/remotes/origin/pr/20/merge)
 > git config core.sparsecheckout # timeout=10
 > git checkout -f e27491b77e327239bf0765975ff0f8445782deb0
First time build. Skipping changelog.
Triggering ghprb-spark-multi-conf » Spark-Ora-JDK7-PV,2.10
ghprb-spark-multi-conf » Spark-Ora-JDK7-PV,2.10 completed with result ABORTED
Notifying upstream projects of job completion
Setting status of 6077776b01fd85da2ef3ccb9917a7e1b9d9cb674 to FAILURE with url http://ci.typesafe.com/job/ghprb-spark-multi-conf/63/ and message: Merged build finished.
```

Test FAILed.

**Comment by typesafe-tools** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://ci.typesafe.com/job/ghprb-spark-multi-conf/64/

**Build Log**
_last 10 lines_

```
[...truncated 11 lines...]
 > git rev-parse refs/remotes/origin/origin/pr/20/merge^{commit} # timeout=10
Checking out Revision e27491b77e327239bf0765975ff0f8445782deb0 (refs/remotes/origin/pr/20/merge)
 > git config core.sparsecheckout # timeout=10
 > git checkout -f e27491b77e327239bf0765975ff0f8445782deb0
First time build. Skipping changelog.
Triggering ghprb-spark-multi-conf » Spark-Ora-JDK7-PV,2.10
ghprb-spark-multi-conf » Spark-Ora-JDK7-PV,2.10 completed with result ABORTED
Notifying upstream projects of job completion
Setting status of 6077776b01fd85da2ef3ccb9917a7e1b9d9cb674 to FAILURE with url http://ci.typesafe.com/job/ghprb-spark-multi-conf/64/ and message: Merged build finished.
```

Test FAILed.

**Comment by nraychaudhuri** [comment]
ok to test

**Comment by typesafe-tools** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://ci.typesafe.com/job/ghprb-spark-multi-conf/65/

**Build Log**
_last 10 lines_

```
[...truncated 18 lines...]
 > git config core.sparsecheckout # timeout=10
 > git checkout -f e27491b77e327239bf0765975ff0f8445782deb0
 > git rev-list e27491b77e327239bf0765975ff0f8445782deb0 # timeout=10
Triggering ghprb-spark-multi-conf » Spark-Ora-JDK7-PV,2.10
Configuration ghprb-spark-multi-conf » Spark-Ora-JDK7-PV,2.10 is still in the queue: Waiting for next available executor on Spark JDK-7 PV (i-a64d7e74)
Configuration ghprb-spark-multi-conf » Spark-Ora-JDK7-PV,2.10 is still in the queue: Waiting for next available executor on Spark-Ora-JDK7-PV
ghprb-spark-multi-conf » Spark-Ora-JDK7-PV,2.10 completed with result FAILURE
Notifying upstream projects of job completion
Setting status of 6077776b01fd85da2ef3ccb9917a7e1b9d9cb674 to FAILURE with url http://ci.typesafe.com/job/ghprb-spark-multi-conf/65/ and message: Merged build finished.
```

Test FAILed.

**Comment by nraychaudhuri** [comment]
ok to test

**Comment by typesafe-tools** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://ci.typesafe.com/job/ghprb-spark-multi-conf/66/

**Build Log**
_last 10 lines_

```
[...truncated 16 lines...]
 > git rev-parse refs/remotes/origin/origin/pr/20/merge^{commit} # timeout=10
Checking out Revision e27491b77e327239bf0765975ff0f8445782deb0 (refs/remotes/origin/pr/20/merge)
 > git config core.sparsecheckout # timeout=10
 > git checkout -f e27491b77e327239bf0765975ff0f8445782deb0
 > git rev-list e27491b77e327239bf0765975ff0f8445782deb0 # timeout=10
Triggering ghprb-spark-multi-conf » Spark-Ora-JDK7-PV,2.10
ghprb-spark-multi-conf » Spark-Ora-JDK7-PV,2.10 completed with result FAILURE
Notifying upstream projects of job completion
Setting status of 6077776b01fd85da2ef3ccb9917a7e1b9d9cb674 to FAILURE with url http://ci.typesafe.com/job/ghprb-spark-multi-conf/66/ and message: Merged build finished.
```

Test FAILed.

**Pull request closed without merging**
