### PR TITLE
Add dynamic allocation to the Spark coarse-grained scheduler.

### PR DESCRIPTION
**Pull request by dragos**

### CODE REVIEW

**Comment by dragos** [comment]
retest this please

**Comment by typesafe-tools** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://ci.typesafe.com/job/ghprb-spark/17/

**Build Log**
_last 10 lines_

```
[...truncated 36 lines...]
[error] (core/compile:scalastyle) errors exist
[error] Total time: 13 s, completed May 5, 2015 9:36:52 AM
[error] /home/ubuntu/workspace/ghprb-spark/core/src/main/scala/org/apache/spark/scheduler/cluster/mesos/CoarseMesosSchedulerBackend.scala:76:6: Public method must have explicit type
[error] (core/compile:scalastyle) errors exist
[error] Total time: 14 s, completed May 5, 2015 9:37:46 AM
[error] Got a return code of 1 on line 125 of the run-tests script.
Build step 'Execute shell' marked build as failure
Notifying upstream projects of job completion
Setting status of b2b51adf30ed370d196e5124dbae7fd1bc251164 to FAILURE with url http://ci.typesafe.com/job/ghprb-spark/17/ and message: Merged build finished.
```

Test FAILed.

**Comment by typesafe-tools** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://ci.typesafe.com/job/ghprb-spark/18/

**Build Log**
_last 10 lines_

```
[...truncated 4308 lines...]
[info] - greaterEq (0 milliseconds)
[info] - plus (0 milliseconds)
[info] - minus (0 milliseconds)
[info] - times (0 milliseconds)
[info] - div (0 milliseconds)
[info] - isMultipleOf (0 milliseconds)Build was aborted
Aborted by Iulian Dragoș
Notifying upstream projects of job completion
Setting status of a68c3bf7fb9621bb9792e605aaf795b7867cbbba to FAILURE with url http://ci.typesafe.com/job/ghprb-spark/18/ and message: Merged build finished.
```

Test FAILed.

**Comment by typesafe-tools** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://ci.typesafe.com/job/ghprb-spark/22/

**Build Log**
_last 10 lines_

```
[...truncated 4446 lines...]
[info] - isZero (0 milliseconds)
[info] - Milliseconds (1 millisecond)
[info] - Seconds (0 milliseconds)
[info] - Minutes (1 millisecond)
[info] RateLimitedOutputStreamSuite:
Build timed out (after 210 minutes). Marking the build as aborted.
Build was aborted
Notifying upstream projects of job completion
Setting status of 4053462bd49ffb240cae5191f1c226b6265d7ce9 to FAILURE with url http://ci.typesafe.com/job/ghprb-spark/22/ and message: Merged build finished.
```

Test FAILed.

**Comment by typesafe-tools** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://ci.typesafe.com/job/ghprb-spark/23/

**Build Log**
_last 10 lines_

```
[...truncated 9582 lines...]
[info] All tests passed.
[info] Passed: Total 540, Failed 0, Errors 0, Passed 540
[error] (streaming/test:test) sbt.TestsFailedException: Tests unsuccessful
[error] (core/test:test) sbt.TestsFailedException: Tests unsuccessful
[error] Total time: 3989 s, completed May 11, 2015 8:18:47 PM
[error] Got a return code of 1 on line 227 of the run-tests script.
Build step 'Execute shell' marked build as failure
Notifying upstream projects of job completion
Setting status of 4e831e27f48ce0f8cc36002af556330518fcc249 to FAILURE with url http://ci.typesafe.com/job/ghprb-spark/23/ and message: Merged build finished.
```

Test FAILed.

**Comment by typesafe-tools** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://ci.typesafe.com/job/ghprb-spark/24/

**Build Log**
_last 10 lines_

```
[...truncated 9675 lines...]
[info] Tests: succeeded 647, failed 0, canceled 0, ignored 19, pending 0
[info] All tests passed.
[info] Passed: Total 650, Failed 0, Errors 0, Passed 650, Ignored 19
[error] (streaming/test:test) sbt.TestsFailedException: Tests unsuccessful
[error] Total time: 4302 s, completed May 12, 2015 3:05:52 PM
[error] Got a return code of 1 on line 227 of the run-tests script.
Build step 'Execute shell' marked build as failure
Notifying upstream projects of job completion
Setting status of 064abf46b4544d9b9912430a3a24e588ef6652c8 to FAILURE with url http://ci.typesafe.com/job/ghprb-spark/24/ and message: Merged build finished.
```

Test FAILed.

**Comment by typesafe-tools** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://ci.typesafe.com/job/ghprb-spark-multi-conf/16/

**Build Log**
_last 10 lines_

```
[...truncated 20 lines...]
First time build. Skipping changelog.
Triggering ghprb-spark-multi-conf » Spark-Ora-JDK7-PV,2.10
Triggering ghprb-spark-multi-conf » Spark-Ora-JDK7-PV,2.11
Configuration ghprb-spark-multi-conf » Spark-Ora-JDK7-PV,2.10 is still in the queue: Waiting for next available executor on Spark JDK-7 PV (i-c840dc18)
Configuration ghprb-spark-multi-conf » Spark-Ora-JDK7-PV,2.10 is still in the queue: Waiting for next available executor on Spark-Ora-JDK7-PV
ghprb-spark-multi-conf » Spark-Ora-JDK7-PV,2.10 completed with result FAILURE
ghprb-spark-multi-conf » Spark-Ora-JDK7-PV,2.11 completed with result FAILURE
Notifying upstream projects of job completion
Setting status of 19920d33cec48e329e7b4498dea0498060c253cd to FAILURE with url http://ci.typesafe.com/job/ghprb-spark-multi-conf/16/ and message: Merged build finished.
```

Test FAILed.

**Comment by typesafe-tools** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://ci.typesafe.com/job/ghprb-spark-multi-conf/17/

**Build Log**
_last 10 lines_

```
[...truncated 18 lines...]
 > git config core.sparsecheckout # timeout=10
 > git checkout -f 44b51f6fc64c3d412b72cdfbcd1b635846b7c7ba
First time build. Skipping changelog.
Triggering ghprb-spark-multi-conf » Spark-Ora-JDK7-PV,2.10
Triggering ghprb-spark-multi-conf » Spark-Ora-JDK7-PV,2.11
ghprb-spark-multi-conf » Spark-Ora-JDK7-PV,2.10 completed with result FAILURE
ghprb-spark-multi-conf » Spark-Ora-JDK7-PV,2.11 completed with result FAILURE
Notifying upstream projects of job completion
Setting status of fdbbc323b78c9fc6e39285640f04b863a4298091 to FAILURE with url http://ci.typesafe.com/job/ghprb-spark-multi-conf/17/ and message: Merged build finished.
```

Test FAILed.

**Comment by typesafe-tools** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://ci.typesafe.com/job/ghprb-spark-multi-conf/18/

**Build Log**
_last 10 lines_

```
[...truncated 18 lines...]
 > git config core.sparsecheckout # timeout=10
 > git checkout -f 44b51f6fc64c3d412b72cdfbcd1b635846b7c7ba
First time build. Skipping changelog.
Triggering ghprb-spark-multi-conf » Spark-Ora-JDK7-PV,2.10
Triggering ghprb-spark-multi-conf » Spark-Ora-JDK7-PV,2.11
ghprb-spark-multi-conf » Spark-Ora-JDK7-PV,2.10 completed with result FAILURE
ghprb-spark-multi-conf » Spark-Ora-JDK7-PV,2.11 completed with result FAILURE
Notifying upstream projects of job completion
Setting status of d50249a3d592f8f9c72ffac6f0a1570b2409c641 to FAILURE with url http://ci.typesafe.com/job/ghprb-spark-multi-conf/18/ and message: Merged build finished.
```

Test FAILed.

**Pull request closed without merging**
