### PR TITLE
testing

### PR DESCRIPTION
**Pull request by nraychaudhuri**

### CODE REVIEW

**Comment by typesafe-tools** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://ci.typesafe.com/job/ghprb-spark-multi-conf/58/

**Build Log**
_last 10 lines_

```
[...truncated 11 lines...]
 > git rev-parse refs/remotes/origin/origin/pr/19/merge^{commit} # timeout=10
Checking out Revision e5e042780d1fa1d2152b94f9df6da1e437e16738 (refs/remotes/origin/pr/19/merge)
 > git config core.sparsecheckout # timeout=10
 > git checkout -f e5e042780d1fa1d2152b94f9df6da1e437e16738
First time build. Skipping changelog.
Triggering ghprb-spark-multi-conf » Spark-Ora-JDK7-PV,2.10
ghprb-spark-multi-conf » Spark-Ora-JDK7-PV,2.10 completed with result FAILURE
Notifying upstream projects of job completion
Setting status of b6ac0e69a35e0755006dc60d0eca85815e06dbbc to FAILURE with url http://ci.typesafe.com/job/ghprb-spark-multi-conf/58/ and message: Merged build finished.
```

Test FAILed.

**Comment by nraychaudhuri** [comment]
ok to test

**Comment by typesafe-tools** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://ci.typesafe.com/job/ghprb-spark-multi-conf/59/

**Build Log**
_last 10 lines_

```
[...truncated 11 lines...]
 > git rev-parse refs/remotes/origin/origin/pr/19/merge^{commit} # timeout=10
Checking out Revision e5e042780d1fa1d2152b94f9df6da1e437e16738 (refs/remotes/origin/pr/19/merge)
 > git config core.sparsecheckout # timeout=10
 > git checkout -f e5e042780d1fa1d2152b94f9df6da1e437e16738
First time build. Skipping changelog.
Triggering ghprb-spark-multi-conf » Spark-Ora-JDK7-PV,2.10
ghprb-spark-multi-conf » Spark-Ora-JDK7-PV,2.10 completed with result FAILURE
Notifying upstream projects of job completion
Setting status of b6ac0e69a35e0755006dc60d0eca85815e06dbbc to FAILURE with url http://ci.typesafe.com/job/ghprb-spark-multi-conf/59/ and message: Merged build finished.
```

Test FAILed.

**Comment by typesafe-tools** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://ci.typesafe.com/job/ghprb-spark-multi-conf/60/

**Build Log**
_last 10 lines_

```
[...truncated 13 lines...]
 > git config core.sparsecheckout # timeout=10
 > git checkout -f aba7f1e1b07458a9e517528c2ff0729aa1436f6b
First time build. Skipping changelog.
Triggering ghprb-spark-multi-conf » Spark-Ora-JDK7-PV,2.10
Aborted
Aborted by Nilanjan Raychaudhuri
Interrupting #60
Notifying upstream projects of job completion
Setting status of 1f59cf3b445354fc0fc6c0176302ac2dd62cfd0d to FAILURE with url http://ci.typesafe.com/job/ghprb-spark-multi-conf/60/ and message: Merged build finished.
```

Test FAILed.

**Comment by nraychaudhuri** [comment]
ok to test

**Comment by typesafe-tools** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://ci.typesafe.com/job/ghprb-spark-multi-conf/61/

**Build Log**
_last 10 lines_

```
[...truncated 11 lines...]
 > git rev-parse refs/remotes/origin/origin/pr/19/merge^{commit} # timeout=10
Checking out Revision aba7f1e1b07458a9e517528c2ff0729aa1436f6b (refs/remotes/origin/pr/19/merge)
 > git config core.sparsecheckout # timeout=10
 > git checkout -f aba7f1e1b07458a9e517528c2ff0729aa1436f6b
First time build. Skipping changelog.
Triggering ghprb-spark-multi-conf » Spark-Ora-JDK7-PV,2.10
ghprb-spark-multi-conf » Spark-Ora-JDK7-PV,2.10 completed with result FAILURE
Notifying upstream projects of job completion
Setting status of 1f59cf3b445354fc0fc6c0176302ac2dd62cfd0d to FAILURE with url http://ci.typesafe.com/job/ghprb-spark-multi-conf/61/ and message: Merged build finished.
```

Test FAILed.

**Comment by nraychaudhuri** [comment]
ok to test

**Comment by typesafe-tools** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://ci.typesafe.com/job/ghprb-spark-multi-conf/62/

**Build Log**
_last 10 lines_

```
[...truncated 11 lines...]
 > git rev-parse refs/remotes/origin/origin/pr/19/merge^{commit} # timeout=10
Checking out Revision aba7f1e1b07458a9e517528c2ff0729aa1436f6b (refs/remotes/origin/pr/19/merge)
 > git config core.sparsecheckout # timeout=10
 > git checkout -f aba7f1e1b07458a9e517528c2ff0729aa1436f6b
First time build. Skipping changelog.
Triggering ghprb-spark-multi-conf » Spark-Ora-JDK7-PV,2.10
ghprb-spark-multi-conf » Spark-Ora-JDK7-PV,2.10 completed with result FAILURE
Notifying upstream projects of job completion
Setting status of 1f59cf3b445354fc0fc6c0176302ac2dd62cfd0d to FAILURE with url http://ci.typesafe.com/job/ghprb-spark-multi-conf/62/ and message: Merged build finished.
```

Test FAILed.

**Pull request closed without merging**
