### PR TITLE
Measures back-pressure on the job queue, and exerts control strategies at Block Generation

### PR DESCRIPTION
**Pull request by huitseeker**

### CODE REVIEW

**Comment by typesafe-tools** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://ci.typesafe.com/job/ghprb-spark-multi-conf/23/

**Build Log**
_last 10 lines_

```
[...truncated 20 lines...]
First time build. Skipping changelog.
Triggering ghprb-spark-multi-conf » Spark-Ora-JDK7-PV,2.10
Triggering ghprb-spark-multi-conf » Spark-Ora-JDK7-PV,2.11
Configuration ghprb-spark-multi-conf » Spark-Ora-JDK7-PV,2.10 is still in the queue: Waiting for next available executor on Spark JDK-7 PV (i-9fb5fe4f)
Configuration ghprb-spark-multi-conf » Spark-Ora-JDK7-PV,2.10 is still in the queue: Waiting for next available executor on Spark-Ora-JDK7-PV
ghprb-spark-multi-conf » Spark-Ora-JDK7-PV,2.10 completed with result FAILURE
ghprb-spark-multi-conf » Spark-Ora-JDK7-PV,2.11 completed with result FAILURE
Notifying upstream projects of job completion
Setting status of 834d24d20bff57c184248e0da9d57650c90da35a to FAILURE with url http://ci.typesafe.com/job/ghprb-spark-multi-conf/23/ and message: Merged build finished.
```

Test FAILed.

**Comment by typesafe-tools** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://ci.typesafe.com/job/ghprb-spark-multi-conf/24/

**Build Log**
_last 10 lines_

```
[...truncated 20 lines...]
First time build. Skipping changelog.
Triggering ghprb-spark-multi-conf » Spark-Ora-JDK7-PV,2.10
Triggering ghprb-spark-multi-conf » Spark-Ora-JDK7-PV,2.11
Configuration ghprb-spark-multi-conf » Spark-Ora-JDK7-PV,2.10 is still in the queue: Waiting for next available executor on Spark JDK-7 PV (i-206332f0)
Configuration ghprb-spark-multi-conf » Spark-Ora-JDK7-PV,2.10 is still in the queue: Waiting for next available executor on Spark-Ora-JDK7-PV
ghprb-spark-multi-conf » Spark-Ora-JDK7-PV,2.10 completed with result FAILURE
ghprb-spark-multi-conf » Spark-Ora-JDK7-PV,2.11 completed with result FAILURE
Notifying upstream projects of job completion
Setting status of 1e684838a366f20bbed90b5bb2cdefb858850846 to FAILURE with url http://ci.typesafe.com/job/ghprb-spark-multi-conf/24/ and message: Merged build finished.
```

Test FAILed.

**Comment by typesafe-tools** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://ci.typesafe.com/job/ghprb-spark-multi-conf/25/

**Build Log**
_last 10 lines_

```
[...truncated 13 lines...]
 > git config core.sparsecheckout # timeout=10
 > git checkout -f ec30a555a731487152a25eda7c1f3026a4eeac39
First time build. Skipping changelog.
Triggering ghprb-spark-multi-conf » Spark-Ora-JDK7-PV,2.10
Triggering ghprb-spark-multi-conf » Spark-Ora-JDK7-PV,2.11
ghprb-spark-multi-conf » Spark-Ora-JDK7-PV,2.10 completed with result FAILURE
ghprb-spark-multi-conf » Spark-Ora-JDK7-PV,2.11 completed with result FAILURE
Notifying upstream projects of job completion
Setting status of 374fb9ce83f1f52bc53244511bc21bb72d3eefd0 to FAILURE with url http://ci.typesafe.com/job/ghprb-spark-multi-conf/25/ and message: Merged build finished.
```

Test FAILed.

**Comment by huitseeker** [comment]
Closing and re-opening with the Reactive API. Please follow-up there: https://github.com/typesafehub/spark/pull/13

**Pull request closed without merging**
