### PR TITLE
Adds measure & transmission of back-pressure from Job queue to Receivers

### PR DESCRIPTION
**Pull request by huitseeker**
The logging statement is in the [next to last](https://github.com/huitseeker/spark/commit/7e9a0b3480f3b9aadc5235d9e9b4c5e2640009d4) commit, suitable for test-bed purposes (but not yet for merging).

### CODE REVIEW

**Comment by typesafe-tools** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://ci.typesafe.com/job/ghprb-spark-multi-conf/5/

**Build Log**
*last 10 lines*

 ```
[...truncated 20 lines...]
First time build. Skipping changelog.
Triggering ghprb-spark-multi-conf » Spark-Ora-JDK7-PV,2.10
Triggering ghprb-spark-multi-conf » Spark-Ora-JDK7-PV,2.11
Configuration ghprb-spark-multi-conf » Spark-Ora-JDK7-PV,2.10 is still in the queue: Waiting for next available executor on Spark JDK-7 PV (i-0e5ebbf2)
Configuration ghprb-spark-multi-conf » Spark-Ora-JDK7-PV,2.10 is still in the queue: Waiting for next available executor on Spark-Ora-JDK7-PV
ghprb-spark-multi-conf » Spark-Ora-JDK7-PV,2.10 completed with result FAILURE
ghprb-spark-multi-conf » Spark-Ora-JDK7-PV,2.11 completed with result FAILURE
Notifying upstream projects of job completion
Setting status of cf0c2588a90c602643cf078d48347ad4c8d11850 to FAILURE with url http://ci.typesafe.com/job/ghprb-spark-multi-conf/5/ and message: Merged build finished.
```

Test FAILed.

**Comment by typesafe-tools** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://ci.typesafe.com/job/ghprb-spark-multi-conf/6/

**Build Log**
*last 10 lines*

 ```
[...truncated 13 lines...]
 > git config core.sparsecheckout # timeout=10
 > git checkout -f b540fcc3dc8768f596148dec121e3f7c6b1c6f47
First time build. Skipping changelog.
Triggering ghprb-spark-multi-conf » Spark-Ora-JDK7-PV,2.10
Triggering ghprb-spark-multi-conf » Spark-Ora-JDK7-PV,2.11
ghprb-spark-multi-conf » Spark-Ora-JDK7-PV,2.10 completed with result FAILURE
ghprb-spark-multi-conf » Spark-Ora-JDK7-PV,2.11 completed with result FAILURE
Notifying upstream projects of job completion
Setting status of 2319088fa0c69f45b2f9ab146e8eb48b8f4c7243 to FAILURE with url http://ci.typesafe.com/job/ghprb-spark-multi-conf/6/ and message: Merged build finished.
```

Test FAILed.

**Comment by typesafe-tools** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://ci.typesafe.com/job/ghprb-spark-multi-conf/7/

**Build Log**
*last 10 lines*

 ```
[...truncated 20 lines...]
First time build. Skipping changelog.
Triggering ghprb-spark-multi-conf » Spark-Ora-JDK7-PV,2.10
Triggering ghprb-spark-multi-conf » Spark-Ora-JDK7-PV,2.11
Configuration ghprb-spark-multi-conf » Spark-Ora-JDK7-PV,2.10 is still in the queue: Waiting for next available executor on Spark JDK-7 PV (i-958e0945)
Configuration ghprb-spark-multi-conf » Spark-Ora-JDK7-PV,2.10 is still in the queue: Waiting for next available executor on Spark-Ora-JDK7-PV
ghprb-spark-multi-conf » Spark-Ora-JDK7-PV,2.10 completed with result FAILURE
ghprb-spark-multi-conf » Spark-Ora-JDK7-PV,2.11 completed with result FAILURE
Notifying upstream projects of job completion
Setting status of 9a0354898ef175788a14fed5a850e6978cc9d48e to FAILURE with url http://ci.typesafe.com/job/ghprb-spark-multi-conf/7/ and message: Merged build finished.
```

Test FAILed.

**Comment by typesafe-tools** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://ci.typesafe.com/job/ghprb-spark-multi-conf/8/

**Build Log**
*last 10 lines*

 ```
[...truncated 18 lines...]
 > git config core.sparsecheckout # timeout=10
 > git checkout -f 1799606c6d94f836a79af8fc3d11298405e270f8
First time build. Skipping changelog.
Triggering ghprb-spark-multi-conf » Spark-Ora-JDK7-PV,2.10
Triggering ghprb-spark-multi-conf » Spark-Ora-JDK7-PV,2.11
ghprb-spark-multi-conf » Spark-Ora-JDK7-PV,2.10 completed with result FAILURE
ghprb-spark-multi-conf » Spark-Ora-JDK7-PV,2.11 completed with result FAILURE
Notifying upstream projects of job completion
Setting status of 7e9a0b3480f3b9aadc5235d9e9b4c5e2640009d4 to FAILURE with url http://ci.typesafe.com/job/ghprb-spark-multi-conf/8/ and message: Merged build finished.
```

Test FAILed.

**Comment by typesafe-tools** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://ci.typesafe.com/job/ghprb-spark-multi-conf/9/

**Build Log**
*last 10 lines*

 ```
[...truncated 13 lines...]
 > git config core.sparsecheckout # timeout=10
 > git checkout -f 1799606c6d94f836a79af8fc3d11298405e270f8
First time build. Skipping changelog.
Triggering ghprb-spark-multi-conf » Spark-Ora-JDK7-PV,2.10
Triggering ghprb-spark-multi-conf » Spark-Ora-JDK7-PV,2.11
ghprb-spark-multi-conf » Spark-Ora-JDK7-PV,2.10 completed with result FAILURE
ghprb-spark-multi-conf » Spark-Ora-JDK7-PV,2.11 completed with result FAILURE
Notifying upstream projects of job completion
Setting status of 6859f932919c09e79c15b0ecbbb94845bbb270be to FAILURE with url http://ci.typesafe.com/job/ghprb-spark-multi-conf/9/ and message: Merged build finished.
```

Test FAILed.

**Comment by typesafe-tools** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://ci.typesafe.com/job/ghprb-spark-multi-conf/10/

**Build Log**
*last 10 lines*

 ```
[...truncated 13 lines...]
 > git config core.sparsecheckout # timeout=10
 > git checkout -f 1799606c6d94f836a79af8fc3d11298405e270f8
First time build. Skipping changelog.
Triggering ghprb-spark-multi-conf » Spark-Ora-JDK7-PV,2.10
Triggering ghprb-spark-multi-conf » Spark-Ora-JDK7-PV,2.11
ghprb-spark-multi-conf » Spark-Ora-JDK7-PV,2.10 completed with result FAILURE
ghprb-spark-multi-conf » Spark-Ora-JDK7-PV,2.11 completed with result FAILURE
Notifying upstream projects of job completion
Setting status of 00ffb5b5a7397925337fe45f8b1f4aac59f40838 to FAILURE with url http://ci.typesafe.com/job/ghprb-spark-multi-conf/10/ and message: Merged build finished.
```

Test FAILed.

**Comment by typesafe-tools** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://ci.typesafe.com/job/ghprb-spark-multi-conf/11/

**Build Log**
*last 10 lines*

 ```
[...truncated 13 lines...]
 > git config core.sparsecheckout # timeout=10
 > git checkout -f 1799606c6d94f836a79af8fc3d11298405e270f8
First time build. Skipping changelog.
Triggering ghprb-spark-multi-conf » Spark-Ora-JDK7-PV,2.10
Triggering ghprb-spark-multi-conf » Spark-Ora-JDK7-PV,2.11
ghprb-spark-multi-conf » Spark-Ora-JDK7-PV,2.10 completed with result FAILURE
ghprb-spark-multi-conf » Spark-Ora-JDK7-PV,2.11 completed with result FAILURE
Notifying upstream projects of job completion
Setting status of fa398da9850b3dd317c7dc4165b5f7f0d0d5fd9f to FAILURE with url http://ci.typesafe.com/job/ghprb-spark-multi-conf/11/ and message: Merged build finished.
```

Test FAILed.

**Comment by typesafe-tools** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://ci.typesafe.com/job/ghprb-spark-multi-conf/12/

**Build Log**
*last 10 lines*

 ```
[...truncated 13 lines...]
 > git config core.sparsecheckout # timeout=10
 > git checkout -f 1799606c6d94f836a79af8fc3d11298405e270f8
First time build. Skipping changelog.
Triggering ghprb-spark-multi-conf » Spark-Ora-JDK7-PV,2.10
Triggering ghprb-spark-multi-conf » Spark-Ora-JDK7-PV,2.11
ghprb-spark-multi-conf » Spark-Ora-JDK7-PV,2.10 completed with result FAILURE
ghprb-spark-multi-conf » Spark-Ora-JDK7-PV,2.11 completed with result FAILURE
Notifying upstream projects of job completion
Setting status of c4b1ef277ce5fa8f19f3fe8b2fdfe71203da6996 to FAILURE with url http://ci.typesafe.com/job/ghprb-spark-multi-conf/12/ and message: Merged build finished.
```

Test FAILed.

**Comment by huitseeker** [comment]
~~Note to self : the behavior of batch processing speed logging is not correct in case _no_ elements are processed during this batch (as of https://github.com/huitseeker/spark/commit/f7bbf86e8511b6a0c61c4d9eb66ed1a1bbba75f3).~~

**Comment by typesafe-tools** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://ci.typesafe.com/job/ghprb-spark-multi-conf/13/

**Build Log**
*last 10 lines*

 ```
[...truncated 20 lines...]
First time build. Skipping changelog.
Triggering ghprb-spark-multi-conf » Spark-Ora-JDK7-PV,2.10
Triggering ghprb-spark-multi-conf » Spark-Ora-JDK7-PV,2.11
Configuration ghprb-spark-multi-conf » Spark-Ora-JDK7-PV,2.10 is still in the queue: Waiting for next available executor on Spark JDK-7 PV (i-760486a6)
Configuration ghprb-spark-multi-conf » Spark-Ora-JDK7-PV,2.10 is still in the queue: Waiting for next available executor on Spark-Ora-JDK7-PV
ghprb-spark-multi-conf » Spark-Ora-JDK7-PV,2.10 completed with result FAILURE
ghprb-spark-multi-conf » Spark-Ora-JDK7-PV,2.11 completed with result FAILURE
Notifying upstream projects of job completion
Setting status of f7bbf86e8511b6a0c61c4d9eb66ed1a1bbba75f3 to FAILURE with url http://ci.typesafe.com/job/ghprb-spark-multi-conf/13/ and message: Merged build finished.
```

Test FAILed.

**Comment by typesafe-tools** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://ci.typesafe.com/job/ghprb-spark-multi-conf/14/

**Build Log**
*last 10 lines*

 ```
[...truncated 18 lines...]
 > git config core.sparsecheckout # timeout=10
 > git checkout -f 0302a0f5e889a4d3a44c4d40b1738bd2d7182dc5
First time build. Skipping changelog.
Triggering ghprb-spark-multi-conf » Spark-Ora-JDK7-PV,2.10
Triggering ghprb-spark-multi-conf » Spark-Ora-JDK7-PV,2.11
ghprb-spark-multi-conf » Spark-Ora-JDK7-PV,2.10 completed with result FAILURE
ghprb-spark-multi-conf » Spark-Ora-JDK7-PV,2.11 completed with result FAILURE
Notifying upstream projects of job completion
Setting status of 38f0f9cbb865a5ab9a625d37b14bf6d3b562a7fb to FAILURE with url http://ci.typesafe.com/job/ghprb-spark-multi-conf/14/ and message: Merged build finished.
```

Test FAILed.

**Comment by typesafe-tools** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://ci.typesafe.com/job/ghprb-spark-multi-conf/15/

**Build Log**
*last 10 lines*

 ```
[...truncated 20 lines...]
First time build. Skipping changelog.
Triggering ghprb-spark-multi-conf » Spark-Ora-JDK7-PV,2.10
Triggering ghprb-spark-multi-conf » Spark-Ora-JDK7-PV,2.11
Configuration ghprb-spark-multi-conf » Spark-Ora-JDK7-PV,2.10 is still in the queue: Waiting for next available executor on Spark JDK-7 PV (i-61048db1)
Configuration ghprb-spark-multi-conf » Spark-Ora-JDK7-PV,2.10 is still in the queue: Waiting for next available executor on Spark-Ora-JDK7-PV
ghprb-spark-multi-conf » Spark-Ora-JDK7-PV,2.10 completed with result FAILURE
ghprb-spark-multi-conf » Spark-Ora-JDK7-PV,2.11 completed with result FAILURE
Notifying upstream projects of job completion
Setting status of c2daea426dc0f9bc448a45d9a758cb11339ccb23 to FAILURE with url http://ci.typesafe.com/job/ghprb-spark-multi-conf/15/ and message: Merged build finished.
```

Test FAILed.

**Comment by dragos** [comment]
Still missing explicit types :)

```
Scalastyle checks failed at following occurrences:
[error] /home/ubuntu/workspace/ghprb-spark-multi-conf/label/Spark-Ora-JDK7-PV/scala_version/2.10/streaming/src/main/scala/org/apache/spark/streaming/receiver/CongestionStrategyImpl.scala:31:15: Public method must have explicit type
[error] (streaming/compile:scalastyle) errors exist
[error] Total time: 13 s, completed May 23, 2015 2:23:45 AM
[error] /home/ubuntu/workspace/ghprb-spark-multi-conf/label/Spark-Ora-JDK7-PV/scala_version/2.10/streaming/src/main/scala/org/apache/spark/streaming/receiver/CongestionStrategyImpl.scala:31:15: Public method must have explicit type
[error] (streaming/compile:scalastyle) errors exist
```

**Comment by typesafe-tools** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://ci.typesafe.com/job/ghprb-spark-multi-conf/19/

**Build Log**
_last 10 lines_

```
[...truncated 20 lines...]
First time build. Skipping changelog.
Triggering ghprb-spark-multi-conf » Spark-Ora-JDK7-PV,2.10
Triggering ghprb-spark-multi-conf » Spark-Ora-JDK7-PV,2.11
Configuration ghprb-spark-multi-conf » Spark-Ora-JDK7-PV,2.10 is still in the queue: Waiting for next available executor on Spark JDK-7 PV (i-a4a0e474)
Configuration ghprb-spark-multi-conf » Spark-Ora-JDK7-PV,2.10 is still in the queue: Waiting for next available executor on Spark-Ora-JDK7-PV
ghprb-spark-multi-conf » Spark-Ora-JDK7-PV,2.10 completed with result FAILURE
ghprb-spark-multi-conf » Spark-Ora-JDK7-PV,2.11 completed with result FAILURE
Notifying upstream projects of job completion
Setting status of b75807c17304aa318a4ac48e670b669388d49467 to FAILURE with url http://ci.typesafe.com/job/ghprb-spark-multi-conf/19/ and message: Merged build finished.
```

Test FAILed.

**Comment by huitseeker** [comment]
Re-opening against a Streaming-specific branch. See:
https://github.com/typesafehub/spark/pull/10

**Comment by typesafe-tools** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://ci.typesafe.com/job/ghprb-spark-multi-conf/20/

**Build Log**
_last 10 lines_

```
[...truncated 20 lines...]
First time build. Skipping changelog.
Triggering ghprb-spark-multi-conf » Spark-Ora-JDK7-PV,2.10
Triggering ghprb-spark-multi-conf » Spark-Ora-JDK7-PV,2.11
Configuration ghprb-spark-multi-conf » Spark-Ora-JDK7-PV,2.10 is still in the queue: Waiting for next available executor on Spark JDK-7 PV (i-03c381d3)
Configuration ghprb-spark-multi-conf » Spark-Ora-JDK7-PV,2.10 is still in the queue: Waiting for next available executor on Spark-Ora-JDK7-PV
ghprb-spark-multi-conf » Spark-Ora-JDK7-PV,2.10 completed with result FAILURE
ghprb-spark-multi-conf » Spark-Ora-JDK7-PV,2.11 completed with result FAILURE
Notifying upstream projects of job completion
Setting status of 4190fbe6f155ab5dee10b6262b57a216959d98fa to FAILURE with url http://ci.typesafe.com/job/ghprb-spark-multi-conf/20/ and message: Merged build finished.
```

Test FAILed.

**Pull request closed without merging**
