### PR TITLE
[SPARK-11714][Mesos] Make Spark on Mesos honor port restrictions on coarse grain mode 2

### PR DESCRIPTION
**Pull request by skonto**
- Make mesos coarse grained scheduler accept port offers
- Propagate them through an env var to the executor
- Enhance startServiceOnPort utils method to take into consideration port restrictions when starting a servic

### CODE REVIEW

**Comment by typesafe-tools** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://ci.typesafe.com/job/ghprb-spark-multi-conf/135/

**Comment by skonto** [comment]
retest this please jenkins

**Comment by typesafe-tools** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://ci.typesafe.com/job/ghprb-spark-multi-conf/136/

**Comment by typesafe-tools** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://ci.typesafe.com/job/ghprb-spark-multi-conf/137/

**Pull request closed without merging**
