### PR TITLE
Test commit

### PR DESCRIPTION
**Pull request by dragos**
# DO NOT MERGE

### CODE REVIEW

**Comment by dragos** [comment]
test this please

**Comment by dragos** [comment]
retest this please

**Comment by dragos** [comment]
retest this please

**Comment by dragos** [comment]
retest this please

**Comment by dragos** [comment]
retest this please

**Comment by dragos** [comment]
retest this please

**Comment by dragos** [comment]
retest this please

**Comment by dragos** [comment]
retest this please

**Comment by dragos** [comment]
retest this please

**Comment by dragos** [comment]
retest this please

**Comment by dragos** [comment]
retest this please

**Comment by dragos** [comment]
retest this please

**Comment by dragos** [comment]
test this please

**Comment by typesafe-tools** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://ci.typesafe.com///job/ghprb-spark/14/
Test PASSed.

**Pull request closed without merging**
